Repository Clay-foundation/model, pull requests merged in 2023-11, with the labels that each got.

#24 Setup LightningCLI trainer script
  README.md
  conda-lock.yml
  environment.yml
  src/README.md
  src/datamodule.py
  src/model.py
  trainer.py
Labels: enhancement

#26 Add pre-commit hooks with ruff formatter/linter rules
  .pre-commit-config.yaml
  pyproject.toml
  trainer.py
Labels: maintenance

#36 Fix lint errors in datacube script
  pyproject.toml
  scripts/datacube.py
Labels: documentation

#46 Bump conda-lock to 2.5.1, add fiona and h5netcdf
  README.md
  conda-lock.yml
  environment.yml
Labels: maintenance

#37 Initial Vision Transformer architecture with MAE decoder
  conda-lock.yml
  environment.yml
  src/README.md
  src/datamodule.py
  src/model.py
  src/model_vit.py
  src/tests/test_model.py
  trainer.py
Labels: model-architecture

#44 Ready for batch
  scripts/datacube.py
  scripts/stack_tile.py
  scripts/tile.py
Labels: data-pipeline

#52 LightningDataModule to load GeoTIFF files
  conda-lock.yml
  environment.yml
  src/README.md
  src/datamodule.py
  src/tests/test_datamodule.py
  src/tests/test_model.py
  trainer.py
Labels: data-pipeline

#53 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation
